# Generated by Django 5.1.3 on 2024-12-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otz', '0002_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
