# Generated by Django 5.1.3 on 2024-12-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otz', '0003_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='mavzu',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='natijasi',
            field=models.CharField(max_length=500),
        ),
    ]
