# Generated by Django 5.1.3 on 2024-12-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otz', '0004_alter_tasks_mavzu_alter_tasks_natijasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='javobgar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='nomer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='topshiriq_kimdan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='topshiriq_turi',
            field=models.CharField(max_length=200),
        ),
    ]
