# Generated by Django 5.1.3 on 2024-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otz', '0005_alter_tasks_javobgar_alter_tasks_nomer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='sana',
            field=models.DateField(),
        ),
    ]
