# Generated by Django 4.2.16 on 2024-12-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otz', '0006_alter_tasks_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='muddat',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='natijasi',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='sana',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
